CREATE DATABASE IF NOT EXISTS reviews;

USE reviews;

CREATE TABLE IF NOT EXISTS product(
  product SERIAL PRIMARY KEY AUTO_INCREMENT NOT NULL,
  page INT DEFAULT 0,
  count INT DEFAULT 5
  -- FOREIGN KEY (id) REFERENCES meta (id)
);

CREATE TABLE IF NOT EXISTS review(
  review_id SERIAL PRIMARY KEY AUTO_INCREMENT NOT NULL,
  rating INT(10) NOT NULL,
  summary VARCHAR(60) NOT NULL,
  recommend BOOLEAN NOT NULL,
  response VARCHAR(100) NOT NULL,
  body VARCHAR(1000) NOT NULL,
  date DATETIME,
  reviewer_name VARCHAR(30) NOT NULL,
  helpfulness TINYINT(4) NOT NULL,
);

CREATE TABLE IF NOT EXISTS photos(
  id SERIAL PRIMARY KEY AUTO_INCREMENT NOT NULL,
  url VARCHAR(100) NOT NULL,
);

CREATE TABLE IF NOT EXISTS Fit(
  id TINYINT(4) NOT NULL,
  value float,
);

CREATE TABLE IF NOT EXISTS Length(
  id TINYINT(4) NOT NULL,
  value float,
);

CREATE TABLE IF NOT EXISTS Comfort(
  id TINYINT(4) NOT NULL,
  value float,
);

CREATE TABLE IF NOT EXISTS Quality(
  id TINYINT(4) NOT NULL,
  value float,
);
-- CREATE TABLE IF NOT EXISTS ratings(
--   id SERIAL PRIMARY KEY AUTO_INCREMENT NOT NULL,
--   url VARCHAR(100) NOT NULL,
-- );

-- CREATE TABLE IF NOT EXISTS meta(
--   id SERIAL PRIMARY KEY AUTO_INCREMENT NOT NULL,
--   url VARCHAR(100) NOT NULL,
-- );

